version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: todo-api-test-db
    environment:
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass123
      POSTGRES_DB: ${DB_NAME_TEST}
    ports:
      - "5434:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todouser"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  test-db-data:
